# frozen_string_literal: true

# Issue #870 characterisation fixture — see docs/notes/20260909-issue-870-per-parameter-binder-superlinear.md.
# Generated by generate.rb at size 6, fan-out 3. Do not hand-edit; regenerate instead.
class Visitor
  def visit_0(node, indent = 0, force: false)
    return node if force
    a0 = visit_1(node, indent + 0, force: true)
    a1 = visit_2(node, indent + 1, force: false)
    a2 = visit_3(node, indent + 2, force: true)
    a0 || a1 || a2
  end
  def visit_1(node, indent = 0, force: false)
    return node if force
    a0 = visit_2(node, indent + 0, force: true)
    a1 = visit_3(node, indent + 1, force: false)
    a2 = visit_4(node, indent + 2, force: true)
    a0 || a1 || a2
  end
  def visit_2(node, indent = 0, force: false)
    return node if force
    a0 = visit_3(node, indent + 0, force: true)
    a1 = visit_4(node, indent + 1, force: false)
    a2 = visit_5(node, indent + 2, force: true)
    a0 || a1 || a2
  end
  def visit_3(node, indent = 0, force: false)
    return node if force
    a0 = visit_4(node, indent + 0, force: true)
    a1 = visit_5(node, indent + 1, force: false)
    a2 = visit_0(node, indent + 2, force: true)
    a0 || a1 || a2
  end
  def visit_4(node, indent = 0, force: false)
    return node if force
    a0 = visit_5(node, indent + 0, force: true)
    a1 = visit_0(node, indent + 1, force: false)
    a2 = visit_1(node, indent + 2, force: true)
    a0 || a1 || a2
  end
  def visit_5(node, indent = 0, force: false)
    return node if force
    a0 = visit_0(node, indent + 0, force: true)
    a1 = visit_1(node, indent + 1, force: false)
    a2 = visit_2(node, indent + 2, force: true)
    a0 || a1 || a2
  end
end
