module Rigor
  module Analysis
    module Reachability
      class ScanCache
        def self.open: (untyped, ?target_ruby: untyped) -> Rigor::Analysis::Reachability::ScanCache
        def self.source_digest: () -> String
        def initialize: (path: untyped, header: untyped) -> void
        def save: () -> nil
      end
    end
  end
end
