module Rigor
  module RbsExtended
    DIRECTIVE_PREFIX: String

    type predicate_edge = :truthy_only | :falsey_only
    type target_kind = :parameter | :self

    class PredicateEffect
      attr_reader edge: predicate_edge
      attr_reader target_kind: target_kind
      attr_reader target_name: Symbol
      attr_reader class_name: String
      attr_reader negative: bool

      def self.new: (edge: predicate_edge, target_kind: target_kind, target_name: Symbol, class_name: String, negative: bool) -> PredicateEffect
      def truthy_only?: () -> bool
      def falsey_only?: () -> bool
      def negative?: () -> bool
    end

    def self?.read_predicate_effects: (untyped method_def) -> Array[PredicateEffect]
    def self?.parse_predicate_annotation: (String string) -> PredicateEffect?

    type assert_condition = :always | :if_truthy_return | :if_falsey_return

    class AssertEffect
      attr_reader condition: assert_condition
      attr_reader target_kind: target_kind
      attr_reader target_name: Symbol
      attr_reader class_name: String
      attr_reader negative: bool

      def self.new: (condition: assert_condition, target_kind: target_kind, target_name: Symbol, class_name: String, negative: bool) -> AssertEffect
      def always?: () -> bool
      def if_truthy_return?: () -> bool
      def if_falsey_return?: () -> bool
      def negative?: () -> bool
    end

    def self?.read_assert_effects: (untyped method_def) -> Array[AssertEffect]
    def self?.parse_assert_annotation: (String string) -> AssertEffect?

    def self?.read_return_type_override: (untyped method_def) -> Type::t?
    def self?.parse_return_type_override: (String string) -> Type::t?
  end
end
