# frozen_string_literal: true

require_relative "rigor/version"
require_relative "rigor/configuration"
require_relative "rigor/trinary"
require_relative "rigor/type"
require_relative "rigor/ast"
require_relative "rigor/environment"
require_relative "rigor/inference/fallback"
require_relative "rigor/inference/fallback_tracer"
require_relative "rigor/inference/acceptance"
require_relative "rigor/inference/rbs_type_translator"
require_relative "rigor/inference/method_dispatcher"
require_relative "rigor/inference/expression_typer"
require_relative "rigor/inference/method_parameter_binder"
require_relative "rigor/inference/statement_evaluator"
require_relative "rigor/scope"
require_relative "rigor/source"
require_relative "rigor/inference/scope_indexer"
require_relative "rigor/inference/coverage_scanner"
require_relative "rigor/analysis/fact_store"
require_relative "rigor/analysis/diagnostic"
require_relative "rigor/analysis/result"
require_relative "rigor/cli"
